* This release

** Coding

*** Command-line interface to lab notebooks 

Allow notebooks to be manipulated from the command line. Specifically
this is to copy and delete result sets from notebooks to tidy them up
for release.

Also need to be able to :

- Manipulate attributes of result sets
- Add [[*Notes for result sets][notes for result sets]] for later annotation

*** Notes for result sets 

Add notes alongside results, as well as the description field.

*** "Test and select" method for result sets

A method on LabNotebook where we can test whether a result set exists
(by tag) and, if so, select it. This would facilitate a design pattern
to only do the experiment that populates the result set if it doesn't
already exist.

** Documentation

*** Pattern for notebooks to avoid conditional cell execution 


Use the [[*"Test and select" method for result sets][test and select method]] to avoid conditional cell execution, by
putting the experiment inside a conditional.

* Ideas dump

** Coding

*** Experimental designs


